## ====================================================================================== ##
# Title:        Comparing Student Temporal Usage for Course Pages and Chapters
#               to Instructors Temporal Use Predictions - Line Graphs and 
# Project:      edX user trajectory analysis
#
#     Copyright 2018 Michael Ginda
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#     
#     http://www.apache.org/licenses/LICENSE-2.0
#     
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#
# Authors:      Michael Ginda
# Affiliation:  Indiana University
# 
# Description:  This script creates visualizations to compare the average student use 
#               time of a course's module to the use times estimated by a course 
#               instructor. As edX courses do not capture instructor time estimates,
#               these were pulled from the course chapter and page description.
#               Average student use time for modules at the lowest level of the
#               edX course hierarchy are summed based on their parent chapter and 
#               (vertical) page module identifier. The script combines the estimated 
#               and summed average student use times, and creates two sets of figures,
#               one for chapter modules and the other for page modules. 
#               
#               Each set includes:              
#                  1) a line graph of the estimated time and average student 
#                     use times; and
#                  2) a bar graph showing the differences between the estimated 
#                     and average student use time.
#                
# File input stack: 
#               1) Course metadata file that describe course identifiers,
#                       - generated by script "edX-a-courseStructure-estimatedTimes.R
#               2) A course structure data set appended with aggregated module 
#                  use statistics for group of student, based on their
#                  learner trajectory networks,
#                       - generated by script "edX-5-StudentEventAgg.R"
#
# Package dependencies: tcltk2, colorspace, ddply, plyr, data.table, ggplot2
#
# Change log:
#   2018.05.17. Initial Code - Environment Set up, load in data for module 
#               analysis, created initial set of visualizations for Page Modules
#   2018.05.18. Updated bar graph labels, legend, and theming; created Chapter Module
#               visualization set; and save updated datasets; streamline functions and 
#               pallettes.
#
## ====================================================================================== ##
#### Environment Setup ####
## Clean the environment 
rm(list=ls()) 
options(scipen=90)
## start timer to track how long the script takes to execute
start <-  proc.time() #save the time (to compute elapsed time of script)
## Load required packages 
require("tcltk2")     #for OS independent GUI file and folder selection
require("colorspace") #ColorSpace color palette selection
require("ddply")      #Aggregation
require("plyr")       #Joins
require("data.table") #TStringExtract
require("ggplot2")    #GGplot 2 graphics library

#### Color Palettes ####
#Manual Color Pallet selection
#pal <-  choose_palette()

#Multi-color categorical color palette for comparing estimated vs real data
pal1 <- function (n, h = c(360, 45), c. = c(100, 17), l = c(46, 93), 
                  power = c(0, 0.866666666666667), fixup = TRUE, gamma = NULL, 
                  alpha = 1, ...) 
                  {
                    if (!is.null(gamma)) 
                      warning("'gamma' is deprecated and has no effect")
                    if (n < 1L) 
                      return(character(0L))
                    h <- rep(h, length.out = 2L)
                    c <- rep(c., length.out = 2L)
                    l <- rep(l, length.out = 2L)
                    power <- rep(power, length.out = 2L)
                    rval <- seq(1, 0, length = n)
                    rval <- hex(polarLUV(L = l[2L] - diff(l) * rval^power[2L], 
                                         C = c[2L] - diff(c) * rval^power[1L], H = h[2L] - diff(h) * 
                                           rval), fixup = fixup, ...)
                    if (!missing(alpha)) {
                      alpha <- pmax(pmin(alpha, 1), 0)
                      alpha <- format(as.hexmode(round(alpha * 255 + 0.0001)), 
                                      width = 2L, upper.case = TRUE)
                      rval <- paste(rval, alpha, sep = "")
                    }
                    return(rval)
                  }

#### Path to Course Analysis Directories ####
#Creates paths used to locate directory course data used in analysis
path_output = tclvalue(tkchooseDirectory())
#Creates a visualization Subdirectory
subDir = c("visualizations")
for(i in 1:length(subDir)){
  if(!file_test("-d", file.path(paste0(path_output,"/analysis/"), subDir[i]))){
    if(file_test("-f", file.path(paste0(path_output,"/analysis/"), subDir[i]))){
      stop("Path can't be created because a file with that name already exists.")
    } else {
      dir.create(file.path(paste0(path_output,"/analysis/"), subDir[i]))
    }
  }
}

#### Load Data ####
#edX Course Chapter Temporal Estimates (L1)
chpFile <- list.files(full.names = TRUE, recursive = F, 
                      path = paste0(path_output,"/analysis/modules/"),
                      pattern = "TimeEstimates\\-L1.csv")
chpEst <- read.csv(file=chpFile)
#edX Course Page Temporal Estimates (L2)
pageFile <- list.files(full.names = TRUE, recursive = F, 
                       path = paste0(path_output,"/analysis/modules/"),
                       pattern = "TimeEstimates\\-L2.csv")
pageEst <- read.csv(file=pageFile)
#Load Module Use Stastics for a Course
mods <- read.csv(file=list.files(full.names = TRUE, recursive = F, 
                                 path = paste0(path_output,"/analysis/modules/"),
                                 pattern = "\\-stds\\+ModuleUseStats.csv"))[c(1:11,16:17)]

#### Aggregateing Module Data to Join to Prediction data ####
#Modules with Zero events are not visualized.
maxStdUsers <- max(mods$unq_stu)
#Aggregate temporal and user data for L2 Modules
modsL1 <- ddply(mods,.(L1),summarize,
                total_time = sum(totalTime),
                total_avgTime  = sum(avgTimeStu),
                avg_subModStdUsers = mean(unq_stu),
                prp_subModStdUsers = mean(unq_stu)/maxStdUsers)

#Aggregate temporal and user data for L2 Modules
modsL2 <- ddply(mods,.(L2),summarize,
                total_time = sum(totalTime),
                total_avgTime  = sum(avgTimeStu),
                avg_subModStdUsers = mean(unq_stu),
                prp_subModStdUsers = mean(unq_stu)/maxStdUsers)
rm(mods)
names(modsL1)[1] <- names(modsL2)[1] <- "id"

#### Join chapter and page temporal estimates with aggregated module data
#Join chpEst to modsL1
chpEst <- join(chpEst,modsL1,by="id")
#Join pageEst to modsL1
pageEst <- join(pageEst,modsL2,by="id")
rm(modsL1,modsL2)

#### Creating fields calculating temporal difference between estimated and average student use time
#Temporal Difference Fields
chpEst$difTime <- chpEst$total_avgTime - chpEst$estTime
chpEst$sign <- ifelse(chpEst$difTime<0,"neg","pos")
chpEst$sign <- factor(chpEst$sign,labels = list("pos"=c("Over Estimate"),"neg"=c("Under Estimate")))

pageEst$difTime <- pageEst$total_avgTime - pageEst$estTime
pageEst$sign <- ifelse(pageEst$difTime<0,"neg","pos")
pageEst$sign <- factor(pageEst$sign,labels = list("pos"=c("Over Estimate"),"neg"=c("Under Estimate")))

#### Save data processing results ####
#Update data file names
chpFile <- strsplit(strsplit(chpFile,split="/")[[1]][10], split="\\.")[[1]][1] 
pageFile <- strsplit(strsplit(pageFile,split="/")[[1]][10], split="\\.")[[1]][1] 
#Write CSVs
write.csv(chpEst, file=paste0(path_output,"/analysis/modules/",chpFile,"-avgStd.csv"),row.names = F)
write.csv(pageEst,file=paste0(path_output,"/analysis/modules/",pageFile,"-avgStd.csv"),row.names = F)

#### Update labels ####
#Update chpEst labels
chpEst$labelTrim <- as.character(trimws(unlist(tstrsplit(as.character(chpEst$label),split="[(]")[1])))
for(i in 1:nrow(chpEst)){
  if(nchar(chpEst[i,]$labelTrim)>22){
    chpEst[i,]$labelTrim <- paste0(trimws(substr(chpEst[i,]$labelTrim,1,22)),"...")
  }
}
#Update pageEst labels
pageEst$label <- trimws(unlist(tstrsplit(as.character(pageEst$label),split="[(]")[1]))
for(i in 1:nrow(pageEst)){
  if(nchar(pageEst[i,]$label)>17){
    pageEst[i,]$label <- paste0(trimws(substr(pageEst[i,]$label,1,17)),"...")
  }
}

#### General Visualization Plot Settings ####
#Theme for ggplot2
theme_set(theme_light())
#Categorical colors 2
catColors <- pal1(5)

#Sets Vertical Line Set for Page Modules by Week of course
vline <- as.data.frame(chpEst[,1:2])
names(vline)[1] <- 'parentID'
vline$label <- as.factor(unlist(tstrsplit(as.character(chpEst$label),split="[(]")[1]))
vline$mod <- 0
for(i in 1:nrow(vline)){
  vline[i,]$mod <- max(pageEst[pageEst$parentID==vline[i,1],]$order)+.5
}

#### Comparing Estimate Page Module Time to Avg Student Page Module Time #### 
#### Fig X: Avg Student Temporal Module Page Use Compared to Estimated Time Use ####
tiff(filename=paste0(path_output,"/analysis/visualizations/figX-L2ModUse-LineGraph-EstTimeStdAvgTime.tif"),
     width = 7, height = 4, units = "in", pointsize = 10, res=300,
     compression = c("none"),  type="cairo", bg = "white")
ggplot(pageEst) +
  geom_line(aes(pageEst$order,pageEst$estTime), linetype = 2) +
  geom_point(aes(pageEst$order,pageEst$estTime), shape=2) +
  geom_line(aes(pageEst$order,pageEst$total_avgTime),linetype = 1) +
  geom_point(aes(pageEst$order,pageEst$total_avgTime), shape=1)
dev.off()  

#### Fig 1 - Inset B: Avg Student Temporal Module Page Use Compared to Estimated Time Use ####
tiff(filename=paste0(path_output,"/analysis/visualizations/fig1-b-L2ModUse-BarGraph-EstTimeStdAvgTime.tif"),
     width = 10, height = 4, units = "in", pointsize = 10, res=300,
     compression = c("none"),  type="cairo", bg = "white")
ggplot(pageEst, aes(x=order, y=difTime)) +
  geom_vline(xintercept=vline[1:nrow(vline),4],linetype=5,alpha=.30) +
  geom_bar(stat="identity",aes(fill=sign))+
  geom_hline(yintercept=0, linetype=1, show.legend = NA)  +
  scale_fill_manual(values=catColors[c(3,1)]) +
  scale_x_continuous(
    expand=c(0.005, 0.005),
    labels=pageEst$label,
    breaks=seq(1,max(pageEst$order),1)) +
  scale_y_continuous(breaks=seq(-20,round(max(pageEst$difTime),0),20))+
  labs(title="B",
       y="Difference in Time (Min.)",
       x="Course Page Module Sequence") +
  guides(fill = guide_legend(
            title = "Difference in Estimate", 
            title.position = "top",
            title.theme = element_text(
              size = 8,
              angle = 0),
            label.theme = element_text(
              size = 6,
              angle = 0),
            reverse = TRUE
            )) +
  theme(axis.text.x = element_text(hjust=1,vjust=.25,size=10, angle=90),
        axis.ticks = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_blank(),
        panel.grid.major.y = element_line(linetype = 4),
        legend.position = c(.95, .99),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(0, 3, 0, 3))
dev.off() 
           
#### Comparing Estimae Chapter Module Time to Avg Student Page Module Time #### 
#### Fig X: Avg Student Temporal Module Chapter Use Compared to Estimated Time Use ####
tiff(filename=paste0(path_output,"/analysis/visualizations/figX-L1ModUse-LineGraph-EstTimeStdAvgTime.tif"),
     width = 10, height = 4, units = "in", pointsize = 10, res=300,
     compression = c("none"),  type="cairo", bg = "white")
ggplot(chpEst) +
  geom_line(aes(chpEst$order,chpEst$estTime), linetype = 2) +
  geom_point(aes(chpEst$order,chpEst$estTime), shape=2) +
  geom_line(aes(chpEst$order,chpEst$total_avgTime), linetype = 1) +
  geom_point(aes(chpEst$order,chpEst$total_avgTime), shape=1)
dev.off()  
#### Fig X: Avg Student Temporal Module Chapter Use Compared to Estimated Time Use ####
tiff(filename=paste0(path_output,"/analysis/visualizations/figX-L1ModUse-BarGraph-EstTimeStdAvgTime.tif"),
     width = 6, height = 4.5, units = "in", pointsize = 10, res=300,
     compression = c("none"),  type="cairo", bg = "white")
ggplot(chpEst, aes(x=order, y=difTime)) +
  geom_bar(stat="identity",aes(fill=sign))+
  geom_hline(yintercept=0, linetype=1, show.legend = NA)  +
  scale_fill_manual(values=catColors[c(3,1)]) +
  scale_x_continuous(
    expand=c(0.01, 0.01),
    labels=chpEst$labelTrim,
    breaks=seq(1,max(chpEst$order),1)) +
  scale_y_continuous(breaks=seq(-60,round(max(chpEst$difTime),0),20))+
  labs(y="Difference in Time (Min.)",
       x="Course Page Module Sequence") +
  guides(fill = guide_legend(
    title = "Difference in Estimate", 
    title.position = "top",
    title.theme = element_text(
      size = 8,
      angle = 0),
    label.theme = element_text(
      size = 6,
      angle = 0),
    reverse = TRUE
  )) +
  theme(axis.text.x = element_text(hjust=1,vjust=.25,size=10, angle=90),
        axis.ticks = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_blank(),
        panel.grid.major.y = element_line(linetype = 4),
        legend.position = c(.95, 1),
        legend.justification = c("right", "top"),
        legend.box.just = "right",
        legend.margin = margin(0, 3, 0, 3))
dev.off() 