## ====================================================================================== ##
# Title:        Course Module Use Analysis
# Project:      edX user trajectory analysis
#
#     Copyright 2017-2018 Michael Ginda
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#     
#     http://www.apache.org/licenses/LICENSE-2.0
#     
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#
# Authors:      Michael Ginda
# Affiliation:  Indiana University
# 
# Description:  This script processes sets of student's learner trajectory networks 
#               from an edX course to an module centered analysis of student activity.
#               The script relies on individual learner transition networks node lists,
#               which captures a students interactions with low level edX learning 
#               modules, based on processed event logs from an EdX course.
#
# File input stack: 
#            1) A list of user identifiers that indicate the student has a 
#               learner trajectory network in the results directory.
#               - {org}+{course}+{term}-auth_user-hasNet.csv
#               - extracted by script, "edX-5-learnerTrajectoryNet.R"
#            2) A "networks" directory containing one or more sets of CSV
#				        student node and edge lists
#               - {userID}-nodes.csv
#               - generated by script by "edX-5-learnerTrajectoryNet.R"
#
# Output files:
#           1) A data table with the results module analysis data for a course:
#               - {org}+{course}+{term}+GRP-{cohort}+{#nets}-stds+ModuleUseStats.csv;
#
# Package dependencies: tcltk, data.table, plyr, stringr, magrittr, zoo
#
# Changelog:
#   2017.11.14. Initial Code - Environment Set up and node agg functions
#   2017.11.15. Node aggregation completed. Edge aggregation function initial 
#               implementation.
#   2017.11.27  Edge aggregation implemented basic transition stats, weights,
#               and student counts 
#   2018.09.11  Updates to code for usability and sharing. Includes updates to: paths,
#               simplified tabulation of node (module) use statistic aggregation based 
#               on learner trajectory networks; set up parameters for cohort analysis;
#               removed aggregate LTN elements from script; revise title and script 
#               description; directory structures for analysis results.
#               
## ====================================================================================== ##
#### Environment setup ####
## Clean the R environment
rm(list=ls()) 
options(scipen=90)

## Load required packages
require("tcltk2")     #for OS independant GUI file and folder selection
require("data.table") #Data Table
require("stringr")    #Stringr 
require("plyr")       #DPLYR
require("magrittr")   #Pipe tool
require("zoo")        #dataPrep

#### Cohort Analysis Parameter Variables #### 
## cohort_sub
#The cohort_sub parameter indicates if a sub-cohort of a course's population is being 
#selected; rather than the full set of active students in the course.
cohort_sub = FALSE

## sub_grp
#The parameter sub_grp indicates the pre-defined sub-groups learner trajectory networks
#to aggregate in an analysis. Three options currently exist: "cert" & "uncert", which
#each aggregate a subset of the student population based on the final grade in the course.
#Bottom 10% of students... "active" indicates all students are processed.
sub_grp = "active"
  
## grade
#The parameter grade indicates the grade required to obtain a certificate in the course.
grade = .65

#### Functions ####
## Node Module Statistical RowSum Tabulation Functions
#tab.vars takes a list of learner trajectory node lists to create an analysis
# of module use in an edX course.
# @param files are a list of learner trajectory node lists that are loaded in by the function.
# @param mods are a list of lower level modules in an edX Course structure. This could be a 
# taken from a course structural list OR an individual learner trajectory network node list.
# @param varCols are the variable columns to be tabulated from the node lists
# @param modVars are the names of the variable columns to be tabulated the node lists
# @return mods are saved back to the original module list
tab.vars <- function(files,mods,varCols,modVars){
  for(i in 1:length(varCols)){
      message("Processing variable ", i, " of ", length(varCols),", which is ",modVars[i])
      print(proc.time() - start)
      temp <- as.data.frame((lapply(files,function(x) read.csv(x)[varCols[i]])))
      rowSums(temp, na.rm=T) %>% as.data.frame() -> temp
      names(temp) <- modVars[i]
      mods <- cbind(mods,temp)
      str(mods[varCols[i]])
  }
  return(mods)
  }


#### Paths ####
#Sets path to processed edX Course Data
path_output = tclvalue(tkchooseDirectory())
path_analysis = paste0(path_output,"/analysis/")
#Creates sub-directories in course directory structure
subDir = c("modules","studentActivity","visualizations","learningObjectives")
for(i in 1:length(subDir)){
  if(!file_test("-d", file.path(path_analysis, subDir[i]))){
    if(file_test("-f", file.path(path_analysis, subDir[i]))){
      stop("Path can't be created because a file with that name already exists.")
    } else {
      dir.create(file.path(path_analysis, subDir[i]))
    }
  }
}

#### Creatuing node and edge file lists for Active Users or Cohorts ####
## start timer to track how long the script takes to execute
start <-  proc.time() #save the time (to compute elapsed time of script)

## Load User List
users <-  read.csv(list.files(full.names = TRUE, recursive = FALSE, 
                          path = paste0(path_output,"/userlists/"),
                          pattern = "-hasNet.csv$"),header=T)
names(users)[1] <- "id"

## Creates fileLists of edX users' learner trajectory network node and edge lists
if(cohort_sub==T){
    #Certified Students 
    while(sub_grp=="cert"){
      nodeFileList <- paste0(path_output,"/networks/nodes/",users[users$grade > grade,]$id,"-nodes.csv")
      #edgeFileList <- paste0(path_output,"/networks/edges/",users[users$grade > grade,]$id,"-edges.csv")
      cohort <-  "Certified"
    }
    #Bottom students
    while(sub_grp=="uncert"){
     nodeFileList <- paste0(path_output,"/networks/nodes/",users[users$grade < grade,]$id,"-nodes.csv")
     #edgeFileList <- paste0(path_output,"/networks/edges/",users[users$grade < grade,]$id,"-edges.csv")
     cohort <-  "Did not Pass"
    }
  } else {
    nodeFileList <- paste0(path_output,"/networks/nodes/",users$id,"-nodes.csv")
    #edgeFileList <- paste0(path_output,"/networks/edges/",users$id,"-edges.csv")
    cohort <- "ActiveEnrolls"
  }
rm(users)

#### Create an initial node list for aggregate module use analysis ####
## Initial node list is used to combine fields across remaining data
mods <- read.csv(nodeFileList[1])[,1:9]

#### Sets output file identifiers ####
#Course Identifier
courseID <- mods$courseID[1]

#Replace with cohort manual entry window OR from filename of data sets of IDs loaded
groupID <- paste0("+GRP-",cohort,"+",length(nodeFileList),"-stds")


#### Tabulate node variables via rowsums ####
#Identifies the variable column to be read in from a set of learner trajectory node list
var_cols = seq(from=10, to=ncol(read.csv(nodeFileList[1])),by=1)

#Identifies the name of the module variable being tabulated from a set of learner trajectory node list
mod_vars = names(read.csv(nodeFileList[1]))[10:ncol(read.csv(nodeFileList[1]))]

#Initial aggregate node row sum tabulations for node variable, for each lower level
#module in an edX course structure.
mods <- tab.vars(files=nodeFileList,mods=mods,varCols=var_cols,modVars=mod_vars)

#### Secondary module use calculations ####
#Proportion of student set that vistit a given module
mods$prpstu <- 0
mods$prpstu <- mods$unq_stu/length(nodeFileList)

##Module Average Events and Temporal Duration Statistics
mods$avg_evt_stu <- 0
mods[mods$unq_stu!=0,]$avg_evt_stu <- mods[mods$unq_stu!=0,]$events/mods[mods$unq_stu!=0,]$unq_stu

#Average time per student
mods$avgTimeStu <- 0
mods[mods$unq_stu!=0,]$avgTimeStu <- mods[mods$unq_stu!=0,]$totalTime/mods[mods$unq_stu!=0,]$unq_stu
#Average time per event
mods$avgTimeEvt <- 0
mods[mods$unq_stu!=0,]$avgTimeEvt <- mods[mods$unq_stu!=0,]$totalTime/mods[mods$unq_stu!=0,]$events

##Problem Module Statistics
#Total Problem Attempts
mods[grepl("problem",mods$module.type)==F,]$attempts <- NA
#Avg Number of Attempts per student
mods$avgAttempts <- NA
mods[mods$unq_stu!=0 & grepl("problem",mods$module.type)==T,]$avgAttempts <- mods[mods$unq_stu!=0 & grepl("problem",mods$module.type)==T,]$attempts/mods[mods$unq_stu!=0 & grepl("problem",mods$module.type)==T,]$unq_stu

#Average Points per Student Attempting Problem
mods$avgPointStu <- NA
mods[mods$unq_stu!=0,]$avgPointStu <- mods[mods$unq_stu!=0,]$points/mods[mods$unq_stu!=0,]$unq_stu
#Max Points earned per problem
mods$maxPointsPrb <- NA
mods[grepl("problem",mods$module.type)==T,]$maxPointsPrb <- ifelse(mods[grepl("problem",mods$module.type)==T,]$avgPointStu>2,3,ifelse(mods[grepl("problem",mods$module.type)==T,]$avgPointStu > 1,2,1)) 

##Video Module Stats
#Avg Load Events
mods$avgLoadEvents <- NA
mods[mods$unq_stu!=0,]$avgLoadEvents <- mods[mods$unq_stu!=0,]$loads/mods[mods$unq_stu!=0,]$unq_stu
#Avg Load Time
mods$avgLoadTime <- NA
mods[mods$unq_stu!=0,]$avgLoadEvents <- mods[mods$unq_stu!=0,]$load_time/mods[mods$unq_stu!=0,]$unq_stu

#Avg Play Events
mods$avgPlayEvents <- NA
mods[mods$unq_stu!=0,]$avgPlayEvents <- mods[mods$unq_stu!=0,]$plays/mods[mods$unq_stu!=0,]$unq_stu
#Avg Play Time
mods$avgPlayTime <- NA
mods[mods$unq_stu!=0,]$avgPlayTime <- mods[mods$unq_stu!=0,]$play_time/mods[mods$unq_stu!=0,]$unq_stu

#Avg Pause Events and Time
mods$avgPauseEvents <- NA
mods[mods$unq_stu!=0,]$avgPauseEvents <- mods[mods$unq_stu!=0,]$pauses/mods[mods$unq_stu!=0,]$unq_stu

mods$avgPauseTime <- NA
mods[mods$unq_stu!=0,]$avgPauseTime <- mods[mods$unq_stu!=0,]$pause_time/mods[mods$unq_stu!=0,]$unq_stu

#Seek Events and Time Stats
mods$avgSeekEvents <- NA
mods[mods$unq_stu!=0,]$avgSeekEvents <- mods[mods$unq_stu!=0,]$seeks/mods[mods$unq_stu!=0,]$unq_stu

mods$avgSeekTime <- NA
mods[mods$unq_stu!=0,]$avgSeekTime <- mods[mods$unq_stu!=0,]$seek_time/mods[mods$unq_stu!=0,]$unq_stu

#### Reorganizes aggregate module analysis ####
mods <- mods[,c(1:10,30,11:13,31,14,32:33,15:20,34,21,35:36,22,37,23,38,24,39,25,40,26,41,27,42,28,43,29,44)]

#### Exports a CSV file of aggregate module analysis for cohort of students ####
write.csv(mods,file=paste0(path_output,"/analysis/modules/",courseID,groupID,"+ModuleUseStats.csv"), row.names = F)
rm(nodeFileList)

#### Finishing details ####
#Indicate completion
message("\n**** Complete! ****\n")

## Script processing time feedback
#print the amount of time the script required
cat("\n\n\nComplete script processing time details (in minutes):\n")
print((proc.time()[3] - start[3])/60)

## Clear environment variables
rm(list=ls())