## ====================================================================================== ##
# Title:        Comparing Student Temporal Usage for Course Pages and Chapters
#               to Instructors Temporal Use Predictions - Line Graphs and 
# Project:      edX user trajectory analysis
#
#     Copyright 2018 Michael Ginda
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#     
#     http://www.apache.org/licenses/LICENSE-2.0
#     
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#
# Authors:      Michael Ginda
# Affiliation:  Indiana University
# 
# Description:  This script creates visualizations based on aggregated statistics of
#               edX course modules (for the lowest level) use and 
#               
#               
#
#                
# File input stack: 
#               1) Course metadata file that describe course identifiers,
#                       - generated by script "edX-a-courseStructure-predictedTimes.R
#               2) A course structure data set appended with aggregated module 
#                  use statistics for group of student, based on their
#                  learner trajectory networks,
#                       - generated by script "edX-5-StudentEventAgg.R"
#
# Package dependencies: tcltk2, colorspace, ddply, plyr, ggplot2
#
# Changelog:
#   2018.05.17. Initial Code - Environment Set up, load in data for module 
#               analysis
#
## ====================================================================================== ##
#### Environment Setup ####
## Clean the environment 
rm(list=ls()) 
options(scipen=90)
## start timer to track how long the script takes to execute
start <-  proc.time() #save the time (to compute elapsed time of script)
## Load required packages 
require("tcltk2")     #for OS independant GUI file and folder selection
require("colorspace") #ColorSpace color pallete selection
require("ddply")      #Aggregation
require("plyr")       #Joins
require("ggplot2")    #GGplot 2 graphics library

#### Functions ####
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)
  
  numPlots = length(plots)
  
  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the  panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                     ncol = cols, nrow = ceiling(numPlots/cols))
  }
  if (numPlots==1) {
    print(plots[[1]])
  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
    
    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
      
      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}

#### Color Palettes ####
#Manual Color Pallet selection
#pal <-  choose_palette()

#Univariate color scale
#Multi-color categorical color palette for comparing estimated vs real data
pal1 <- function (n, h = c(360, 45), c. = c(100, 17), l = c(46, 93), 
                  power = c(0, 0.866666666666667), fixup = TRUE, gamma = NULL, 
                  alpha = 1, ...) 
                  {
                    if (!is.null(gamma)) 
                      warning("'gamma' is deprecated and has no effect")
                    if (n < 1L) 
                      return(character(0L))
                    h <- rep(h, length.out = 2L)
                    c <- rep(c., length.out = 2L)
                    l <- rep(l, length.out = 2L)
                    power <- rep(power, length.out = 2L)
                    rval <- seq(1, 0, length = n)
                    rval <- hex(polarLUV(L = l[2L] - diff(l) * rval^power[2L], 
                                         C = c[2L] - diff(c) * rval^power[1L], H = h[2L] - diff(h) * 
                                           rval), fixup = fixup, ...)
                    if (!missing(alpha)) {
                      alpha <- pmax(pmin(alpha, 1), 0)
                      alpha <- format(as.hexmode(round(alpha * 255 + 0.0001)), 
                                      width = 2L, upper.case = TRUE)
                      rval <- paste(rval, alpha, sep = "")
                    }
                    return(rval)
                  }

#Divergent-color for comparing temporal differences
#Blue/Grey/Green
pal2 <- function (n, h = c(248, 93), c = 100, l = c(70, 96), power = 1.21111111111111, 
                  fixup = TRUE, gamma = NULL, alpha = 1, ...) 
                    {
                      if (!is.null(gamma)) 
                        warning("'gamma' is deprecated and has no effect")
                      if (n < 1L) 
                        return(character(0L))
                      h <- rep(h, length.out = 2L)
                      c <- c[1L]
                      l <- rep(l, length.out = 2L)
                      power <- rep(power, length.out = 2L)
                      rval <- seq(1, -1, length = n)
                      rval <- hex(polarLUV(L = l[2L] - diff(l) * abs(rval)^power[2L], 
                                           C = c * abs(rval)^power[1L], H = ifelse(rval > 0, h[1L], 
                                                                                   h[2L])), fixup = fixup, ...)
                      if (!missing(alpha)) {
                        alpha <- pmax(pmin(alpha, 1), 0)
                        alpha <- format(as.hexmode(round(alpha * 255 + 0.0001)), 
                                        width = 2L, upper.case = TRUE)
                        rval <- paste(rval, alpha, sep = "")
                      }
                      return(rval)
                    }

#### Path to Course Analysis Directories ####
#Creates paths used to locate directory course data used in analyis
path_output = tclvalue(tkchooseDirectory())
#Creates a visualization Subdirectory
subDir = c("visualizations")
for(i in 1:length(subDir)){
  if(!file_test("-d", file.path(paste0(path_output,"/analysis/"), subDir[i]))){
    if(file_test("-f", file.path(paste0(path_output,"/analysis/"), subDir[i]))){
      stop("Path can't be created because a file with that name already exists.")
    } else {
      dir.create(file.path(paste0(path_output,"/analysis/"), subDir[i]))
    }
  }
}

#### Load Data ####
#edX Course Chapter Temporal Estimates (L1)
chpEst <- read.csv(file=list.files(full.names = TRUE, recursive = F, 
                                       path = paste0(path_output,"/analysis/modules/"),
                                       pattern = "TimeEstimates\\-L1.csv"))
#edX Course Page Temporal Estimates (L2)
pageEst <- read.csv(file=list.files(full.names = TRUE, recursive = F, 
                                 path = paste0(path_output,"/analysis/modules/"),
                                 pattern = "TimeEstimates\\-L2.csv"))
#Load Module Use Stastics for a Course
mods <- read.csv(file=list.files(full.names = TRUE, recursive = F, 
                                 path = paste0(path_output,"/analysis/modules/"),
                                 pattern = "\\-stds\\+ModuleUseStats.csv"))[c(1:11,16:17)]

#### Aggregateing Module Data to Join to Prediction data ####
#Modules with Zero events are not visualized.
maxStdUsers <- max(mods$unq_stu)
#Aggregate temporal and user data for L2 Modules
modsL1 <- ddply(mods,.(L1),summarize,
                total_time = sum(totalTime),
                total_avgTime  = sum(avgTimeStu),
                avg_subModStdUsers = mean(unq_stu),
                prp_subModStdUsers = mean(unq_stu)/maxStdUsers)

#Aggregate temporal and user data for L2 Modules
modsL2 <- ddply(mods,.(L2),summarize,
                total_time = sum(totalTime),
                total_avgTime  = sum(avgTimeStu),
                avg_subModStdUsers = mean(unq_stu),
                prp_subModStdUsers = mean(unq_stu)/maxStdUsers)
rm(mods)
names(modsL1)[1] <- names(modsL2)[1] <- "id"

#### Join chapter and page temporal estimates with aggregated module data
#Join chpEst to modsL1
chpEst <- join(chpEst,modsL1,by="id")
#Join chpEst to modsL1
pageEst <- join(pageEst,modsL2,by="id")
rm(modsL1,modsL2)

#### Visualization Plotting Settings ####
#Sets Vertical Line Set for Modules by Week of course
vline <- as.data.frame(unique(mod_unq$L1))
names(vline)[1] <- "L1"
vline$mod <- NA
for(i in 1:nrow(vline)){
  vline[i,]$mod <- max(mod_unq[mod_unq$L1==vline[i,1],]$order)
}

#### Sets global GGplot2 themes and palletes ####
theme_set(theme_light())
##Color Scales and setting for graphs
strip <- c("#DCDCDC") #Grey
#Categorical colors 2
catColors <- pal1(2)
#Bivariate
biColor <- pal2(21)
#Removes color scale functions
rm(pal1,pal2)

#### Visualizations ####



